
#sa SOURCE_CPP_LIST: .cpp=.o kaze kod svih filove iz cpp liste .cpp zameni sa .o tj tamo gde je .cpp stavi .o -> main.cpp -> main.o itd 
#sa notdir izbaci cpp/
#sa addprefix doda build/
#i to izmenjeno doda u OBJECTS_LIST

#sa -Ih kazemo da g++ potrazi include file-ove u h folderu

BUILD_DIR= build

SOURCE_CPP_LIST = \
cpp/main.cpp \
cpp/RingBuffer.cpp \
cpp/Semaphore.cpp

OBJECTS_LIST=
OBJECTS_LIST+= $(addprefix $(BUILD_DIR)/,$(notdir $(SOURCE_CPP_LIST:.cpp=.o)))
#posle ovoga OBJECTS_LIST ima build/main.o itd

vpath %.cpp ./cpp #kazemo mikefile-u da pretrazuje i .cpp folder za ulazne file-ove jer on implicitno prerazuje samo folder gde je sam Makefile

all: clean $(BUILD_DIR) exe

exe: makeExec
	./exec




makeExec : $(OBJECTS_LIST) makefile
	g++ -pthread -o exec $(OBJECTS_LIST)


$(BUILD_DIR)/%.o : $(BUILD_DIR)/%.s 
	as  -o $(@) $(<)




$(BUILD_DIR)/%.s : $(BUILD_DIR)/%.i 
	g++ -S -o $(@) $(<)



$(BUILD_DIR)/%.i : %.cpp makefile
	cpp -MMD -MP -Ih -o $(@) $(<)




$(BUILD_DIR):
	mkdir $(@)


clean:
	rm -rf $(BUILD_DIR)


-include $(wildcard $(BUILD_DIR)/*.d)